### ISSUE TITLE
Custom dataset training

### ISSUE THREAD

**Issue by kidpaul94** [XuyangBai/D3Feat.pytorch#5]
Hi, 
Thank you for your great work! 
I just wonder whether training for a custom dataset (.ply files) is supported for the pytorch version since you specifically wrote that this version only supports 3DMatch currently.

**Comment by XuyangBai** [comment]
Hi, Thanks for your interest in this work. Since we need point-to-point correspondences for contrastive loss, you should have the point cloud pairs as well as the gt transformation between point cloud pairs for your own dataset. Once you have prepared such data, you could implement the dataset class following the released one.

**Comment by kidpaul94** [comment]
Thank you for your quick response! I'll try that.
